// Auto-generated by build.rs - do not edit
pub const LISTS: &[&str] = &[
    include_str!("lists/Adaway.txt"),
    include_str!("lists/AdguardDNS.txt"),
    include_str!("lists/Easylist.txt"),
    include_str!("lists/Easyprivacy.txt"),
    include_str!("lists/Phishing_army_blocklist_extended.txt"),
];
